name: "Commit Message Check"
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Commit Message
        run: |
          # Take the title of last commit
          MSG=$(git log -1 --pretty=%s)
          echo "Check the message: $MSG"
          
          # Regex: ^# (start with #), [0-9]+ (one or more numbers), , (comma), \  (space)
          if [[ ! $MSG =~ ^#[0-9]+,\ .+$ ]]; then
            echo "ERROR: Message must be in format '#123, text'"
            exit 1
          fi
          
          # Chec the lenght
          if [ ${#MSG} -gt 30 ]; then
            echo "ERROR: Message too long (max 40 characters)."
            exit 1
          fi
